import { group, word } from "../../lib/span";
import type { Chapter } from "../../types";

const translation =
  "I bow to that Dhanvantari who holds, in his four beautiful arms, the conch, the discus, a leech, and the pot of nectar; whose diadem shines with a fine, pure, lovely cloth, whose eyes are lotuses; whose body gleams like a dark rain-cloud, whose hips are adorned with a beautiful yellow garment; whose play is a raging wildfire that burns down the whole forest of diseases.";

export const dhanvantari: Chapter = {
  id: "dhanvantari",
  titleDev: "धन्वन्तरिः",
  titleIast: "dhanvantariḥ",
  titleEn: "Dhanvantari",
  status: "ready",
  translation,
  glossary: [
    { term: "śaṅkham", meaning: "conch" },
    { term: "cakram", meaning: "discus" },
    { term: "jalaukām", meaning: "leech" },
    { term: "dadhat", meaning: "holding" },
    { term: "amṛtaghaṭam", meaning: "the pot of nectar" },
    { term: "cārudorbhiḥ", meaning: "with beautiful arms" },
    { term: "caturbhiḥ", meaning: "with four" },
    { term: "sūkṣmasvacchātihṛdyāṃśuka", meaning: "a fine, pure, most charming cloth" },
    { term: "parivilasanmaulim", meaning: "whose diadem is shining all around" },
    { term: "ambhojanetram", meaning: "lotus-eyed" },
    { term: "kālāmbhodojjvalāṅgam", meaning: "whose body gleams like a dark rain-cloud" },
    { term: "kaṭitaṭavilasaccārupītāmbarāḍhyam", meaning: "whose hip is adorned with a beautiful yellow garment" },
    { term: "vande", meaning: "I bow" },
    { term: "dhanvantarim", meaning: "to Dhanvantari" },
    { term: "tam", meaning: "that one" },
    { term: "nikhilagadavanaprauḍhadāvāgnilīlam", meaning: "whose sport is a mighty forest-fire to the entire forest of diseases" },
  ],
  root: group("dh-verse", "verse", translation, [
    group(
      "dh-pada1",
      "phrase",
      "holding conch, discus, leech, and the nectar-pot in four beautiful arms",
      [
        word("dh-sankham", "conch", [["शङ्", "śaṅ"], ["खं", "khaṃ"]]),
        word("dh-cakram", "discus", [["च", "ca"], ["क्रं", "kraṃ"]]),
        word("dh-jalaukam", "leech", [
          ["ज", "ja"],
          ["लौ", "lau"],
          ["कां", "kāṃ"],
        ]),
        word("dh-amrtaghatam", "holding the pot of nectar", [
          ["द", "da"],
          ["ध", "dha"],
          ["द", "da"],
          ["मृ", "mṛ"],
          ["त", "ta"],
          ["घ", "gha"],
          ["टं", "ṭaṃ"],
        ]),
        word("dh-carudorbhih", "with beautiful arms", [
          ["चा", "cā"],
          ["रु", "ru"],
          ["दो", "do"],
          ["र्भिश्", "rbhiś"],
        ], { trailing: "" }),
        word("dh-caturbhih", "with four", [
          ["च", "ca"],
          ["तु", "tu"],
          ["र्भिः", "rbhiḥ"],
        ], { trailing: " ।", lineBreakAfter: true }),
      ],
    ),
    group(
      "dh-pada2",
      "phrase",
      "whose diadem shines with a fine, pure, lovely cloth; lotus-eyed",
      [
        word("dh-amsuka", "a fine, pure, most charming cloth", [
          ["सू", "sū"],
          ["क्ष्म", "kṣma"],
          ["स्व", "sva"],
          ["च्छा", "cchā"],
          ["ति", "ti"],
          ["हृ", "hṛ"],
          ["द्यां", "dyāṃ"],
          ["शु", "śu"],
          ["क", "ka"],
        ]),
        word("dh-maulim", "whose diadem is shining all around", [
          ["प", "pa"],
          ["रि", "ri"],
          ["वि", "vi"],
          ["ल", "la"],
          ["सन्", "san"],
          ["मौ", "mau"],
          ["लि", "li"],
          ["म", "ma"],
        ], { trailing: "" }),
        word("dh-ambhoja", "lotus-eyed", [
          ["म्भो", "mbho"],
          ["ज", "ja"],
          ["ने", "ne"],
          ["त्रम्", "tram"],
        ], { trailing: " ।", lineBreakAfter: true }),
      ],
    ),
    group(
      "dh-pada3",
      "phrase",
      "body gleaming like a dark rain-cloud; hips adorned with a yellow garment",
      [
        word("dh-kala", "whose body gleams like a dark rain-cloud", [
          ["का", "kā"],
          ["लाम्", "lām"],
          ["भो", "bho"],
          ["दो", "do"],
          ["ज्ज्व", "jjva"],
          ["लाङ्", "lāṅ"],
          ["गं", "gaṃ"],
        ]),
        word("dh-pita", "whose hip is adorned with a beautiful yellow garment", [
          ["क", "ka"],
          ["टि", "ṭi"],
          ["त", "ta"],
          ["ट", "ṭa"],
          ["वि", "vi"],
          ["ल", "la"],
          ["सच्चा", "saccā"],
          ["रु", "ru"],
          ["पी", "pī"],
          ["ता", "tā"],
          ["म्ब", "mba"],
          ["रा", "rā"],
          ["ढ्यम्", "ḍhyam"],
        ], { trailing: " ।", lineBreakAfter: true }),
      ],
    ),
    group(
      "dh-pada4",
      "phrase",
      "I bow to that Dhanvantari, whose play is a wildfire to the forest of diseases",
      [
        word("dh-vande", "I bow", [["व", "va"], ["न्दे", "nde"]]),
        word("dh-dhanvantarim", "to Dhanvantari", [
          ["ध", "dha"],
          ["न्व", "nva"],
          ["न्ति", "nti"],
          ["रिं", "riṃ"],
        ]),
        word("dh-tam", "that one", [["तं", "taṃ"]]),
        word("dh-nikhila", "whose sport is a mighty forest-fire to the entire forest of diseases", [
          ["नि", "ni"],
          ["खि", "khi"],
          ["ल", "la"],
          ["ग", "ga"],
          ["द", "da"],
          ["व", "va"],
          ["न", "na"],
          ["प्रौ", "prau"],
          ["ढ", "ḍha"],
          ["दा", "dā"],
          ["वा", "vā"],
          ["ग्नि", "gni"],
          ["ली", "lī"],
          ["लम्", "lam"],
        ], { trailing: " ॥" }),
      ],
    ),
  ]),
};
