import { group, word } from "../../lib/span";
import type { Chapter } from "../../types";

const translation =
  "She who is white like jasmine, the moon, and a garland of snow; who is wrapped in pure white cloth; whose hands are adorned with the excellent neck of the vīṇā; who sits on a white lotus; who is ever praised by the gods beginning with Brahmā, Acyuta, and Śaṅkara — may that Blessed Lady Sarasvatī, who utterly removes dullness, protect me.";

export const sarasvati: Chapter = {
  id: "sarasvati",
  titleDev: "सरस्वती",
  titleIast: "sarasvatī",
  titleEn: "Sarasvatī",
  status: "ready",
  translation,
  glossary: [
    { term: "yā", meaning: "she who" },
    { term: "kundendutuṣārahāradhavalā", meaning: "white like kunda, the moon, and a garland of snow" },
    { term: "śubhravastrāvṛtā", meaning: "wrapped in pure white cloth" },
    { term: "vīṇāvaradaṇḍamaṇḍitakarā", meaning: "whose hands are adorned with the excellent neck of the vīṇā" },
    { term: "śvetapadmāsanā", meaning: "who sits on a white lotus" },
    { term: "brahmācyutaśaṅkaraprabhṛtibhiḥ", meaning: "by (the gods) beginning with Brahmā, Acyuta, and Śaṅkara" },
    { term: "devaiḥ", meaning: "by the gods" },
    { term: "sadā", meaning: "always" },
    { term: "vanditā", meaning: "praised" },
    { term: "sā", meaning: "she" },
    { term: "mām", meaning: "me" },
    { term: "pātu", meaning: "may she protect" },
    { term: "sarasvatī", meaning: "Sarasvatī" },
    { term: "bhagavatī", meaning: "Blessed Lady" },
    { term: "niḥśeṣajāḍyāpahā", meaning: "who utterly removes dullness" },
  ],
  root: group("sv-verse", "verse", translation, [
    group("sv-form", "phrase", "white like jasmine, moon, and snow-garland; wrapped in white; vīṇā in hand; seated on a white lotus", [
      word("sv-ya1", "she who", [["या", "yā"]]),
      word("sv-kundendu", "white like kunda, the moon, and a garland of snow", [
        ["कु", "ku"],
        ["न्दे", "nde"],
        ["न्दु", "ndu"],
        ["तु", "tu"],
        ["षा", "ṣā"],
        ["र", "ra"],
        ["हा", "hā"],
        ["र", "ra"],
        ["ध", "dha"],
        ["व", "va"],
        ["ला", "lā"],
      ]),
      word("sv-ya2", "she who", [["या", "yā"]]),
      word("sv-subhra", "wrapped in pure white cloth", [
        ["शु", "śu"],
        ["भ्र", "bhra"],
        ["व", "va"],
        ["स्त्रा", "strā"],
        ["वृ", "vṛ"],
        ["ता", "tā"],
      ], { lineBreakAfter: true }),
      word("sv-ya3", "she who", [["या", "yā"]]),
      word("sv-vina", "whose hands are adorned with the excellent neck of the vīṇā", [
        ["वी", "vī"],
        ["णा", "ṇā"],
        ["व", "va"],
        ["र", "ra"],
        ["द", "da"],
        ["ण्ड", "ṇḍa"],
        ["म", "ma"],
        ["ण्डि", "ṇḍi"],
        ["त", "ta"],
        ["क", "ka"],
        ["रा", "rā"],
      ]),
      word("sv-ya4", "she who", [["या", "yā"]]),
      word("sv-sveta", "who sits on a white lotus", [
        ["श्वे", "śve"],
        ["त", "ta"],
        ["प", "pa"],
        ["द्मा", "dmā"],
        ["स", "sa"],
        ["ना", "nā"],
      ], { trailing: " ।", lineBreakAfter: true }),
    ]),
    group("sv-ask", "phrase", "ever praised by Brahmā, Acyuta, and Śaṅkara — may Sarasvatī protect me and remove all dullness", [
      word("sv-ya5", "she who", [["या", "yā"]]),
      word("sv-brahma", "by the gods beginning with Brahmā, Acyuta, and Śaṅkara", [
        ["ब्र", "bra"],
        ["ह्मा", "hmā"],
        ["च्यु", "cyu"],
        ["त", "ta"],
        ["शङ्", "śaṅ"],
        ["क", "ka"],
        ["र", "ra"],
        ["प्र", "pra"],
        ["भृ", "bhṛ"],
        ["ति", "ti"],
        ["भिर्", "bhir"],
      ], { trailing: "" }),
      word("sv-devaih", "by the gods", [["दे", "de"], ["वैः", "vaiḥ"]]),
      word("sv-sada", "always", [["स", "sa"], ["दा", "dā"]]),
      word("sv-vandita", "praised", [["व", "va"], ["न्दि", "ndi"], ["ता", "tā"]], {
        lineBreakAfter: true,
      }),
      word("sv-sa", "she", [["सा", "sā"]]),
      word("sv-mam", "me", [["मां", "māṃ"]]),
      word("sv-patu", "may she protect", [["पा", "pā"], ["तु", "tu"]]),
      word("sv-sarasvati", "Sarasvatī", [
        ["स", "sa"],
        ["र", "ra"],
        ["स्व", "sva"],
        ["ती", "tī"],
      ]),
      word("sv-bhagavati", "Blessed Lady", [
        ["भ", "bha"],
        ["ग", "ga"],
        ["व", "va"],
        ["ती", "tī"],
      ]),
      word("sv-nihshesha", "who utterly removes dullness", [
        ["निः", "niḥ"],
        ["शे", "śe"],
        ["ष", "ṣa"],
        ["जा", "jā"],
        ["ड्या", "ḍyā"],
        ["प", "pa"],
        ["हा", "hā"],
      ], { trailing: " ॥" }),
    ]),
  ]),
};
