import { libraryClusterItems } from "../../lib/clusters";
import type { QuizDeck, QuizDeckItem, QuizUnit } from "../../lib/quiz";

function letters(
  unit: QuizUnit,
  rows: Array<[id: string, dev: string, iast: string, meaning?: string]>,
): QuizDeckItem[] {
  return rows.map(([id, dev, iast, meaning]) => ({
    id,
    dev,
    iast,
    unit,
    meaning,
  }));
}

const howItWorksItems = letters("akshara", [
  ["default-vowel", "क", "a", "Default vowel on a Devanagari consonant (as in क)"],
  ["ka-inherent", "क", "ka", "क with its default vowel"],
  ["k-virama", "क्", "k", "क with the default vowel blocked"],
  ["virama-name", "्", "virāma", "Name of the mark that blocks the default a"],
  ["syllable-script", "देवनागरी", "syllable", "Devanagari groups symbols into this kind of unit"],
  ["direction", "देवनागरी", "left to right", "Direction Devanagari is written"],
  ["de", "दे", "de", "First syllable of देवनागरी"],
  ["va", "व", "va", "Second syllable of देवनागरी"],
  ["naa", "ना", "nā", "Third syllable of देवनागरी"],
  ["ga", "ग", "ga", "Fourth syllable of देवनागरी"],
  ["rii", "री", "rī", "Last syllable of देवनागरी"],
  ["ska", "स्क", "ska", "Cluster s + ka, as in संस्कृत"],
  ["sam", "सं", "saṃ", "स with anusvāra"],
]);

const vowelConsonantItems = letters("akshara", [
  ["a", "अ", "a"],
  ["aa", "आ", "ā"],
  ["i", "इ", "i"],
  ["ii", "ई", "ī"],
  ["u", "उ", "u"],
  ["uu", "ऊ", "ū"],
  ["r", "ऋ", "ṛ"],
  ["rr", "ॠ", "ṝ"],
  ["l", "ऌ", "ḷ"],
  ["ll", "ॡ", "ḹ"],
  ["e", "ए", "e"],
  ["ai", "ऐ", "ai"],
  ["o", "ओ", "o"],
  ["au", "औ", "au"],
  ["ka", "क", "ka"],
  ["kha", "ख", "kha"],
  ["ga", "ग", "ga"],
  ["gha", "घ", "gha"],
  ["nga", "ङ", "ṅa"],
  ["ca", "च", "ca"],
  ["cha", "छ", "cha"],
  ["ja", "ज", "ja"],
  ["jha", "झ", "jha"],
  ["nya", "ञ", "ña"],
  ["tta", "ट", "ṭa"],
  ["ttha", "ठ", "ṭha"],
  ["dda", "ड", "ḍa"],
  ["ddha", "ढ", "ḍha"],
  ["nna", "ण", "ṇa"],
  ["ta", "त", "ta"],
  ["tha", "थ", "tha"],
  ["da", "द", "da"],
  ["dha", "ध", "dha"],
  ["na", "न", "na"],
  ["pa", "प", "pa"],
  ["pha", "फ", "pha"],
  ["ba", "ब", "ba"],
  ["bha", "भ", "bha"],
  ["ma", "म", "ma"],
  ["ya", "य", "ya"],
  ["ra", "र", "ra"],
  ["la", "ल", "la"],
  ["va", "व", "va"],
  ["sha", "श", "śa"],
  ["ssa", "ष", "ṣa"],
  ["sa", "स", "sa"],
  ["ha", "ह", "ha"],
]);

const ramaItems = letters("word", [
  ["sg1", "रामः", "rāmaḥ", "Rāma as the subject (one)"],
  ["sg2", "रामम्", "rāmam", "Rāma as the object (one)"],
  ["sg3", "रामेण", "rāmeṇa", "with (one) Rāma"],
  ["sg4", "रामाय", "rāmāya", "for (one) Rāma"],
  ["sg5", "रामात्", "rāmāt", "from (one) Rāma"],
  ["sg6", "रामस्य", "rāmasya", "of (one) Rāma"],
  ["sg7", "रामे", "rāme", "in (one) Rāma"],
  ["sg8", "राम", "rāma", "O Rāma (one)"],
  ["du1", "रामौ", "rāmau", "two Rāmas as the subject"],
  ["du2", "रामौ", "rāmau", "two Rāmas as the object"],
  ["du3", "रामाभ्याम्", "rāmābhyām", "with two Rāmas"],
  ["du4", "रामाभ्याम्", "rāmābhyām", "for two Rāmas"],
  ["du5", "रामाभ्याम्", "rāmābhyām", "from two Rāmas"],
  ["du6", "रामयोः", "rāmayoḥ", "of two Rāmas"],
  ["du7", "रामयोः", "rāmayoḥ", "in two Rāmas"],
  ["du8", "रामौ", "rāmau", "O two Rāmas"],
  ["pl1", "रामाः", "rāmāḥ", "Rāmas as the subject (many)"],
  ["pl2", "रामान्", "rāmān", "Rāmas as the object (many)"],
  ["pl3", "रामैः", "rāmaiḥ", "with (many) Rāmas"],
  ["pl4", "रामेभ्यः", "rāmebhyaḥ", "for (many) Rāmas"],
  ["pl5", "रामेभ्यः", "rāmebhyaḥ", "from (many) Rāmas"],
  ["pl6", "रामाणाम्", "rāmāṇām", "of (many) Rāmas"],
  ["pl7", "रामेषु", "rāmeṣu", "in (many) Rāmas"],
  ["pl8", "रामाः", "rāmāḥ", "O Rāmas (many)"],
]);

const vowelMarkItems = letters("matra", [
  ["ka", "क", "ka"],
  ["kaa", "का", "kā"],
  ["ki", "कि", "ki"],
  ["kii", "की", "kī"],
  ["ku", "कु", "ku"],
  ["kuu", "कू", "kū"],
  ["kr", "कृ", "kṛ"],
  ["krr", "कॄ", "kṝ"],
  ["kl", "कॢ", "kḷ"],
  ["kll", "कॣ", "kḹ"],
  ["ke", "के", "ke"],
  ["kai", "कै", "kai"],
  ["ko", "को", "ko"],
  ["kau", "कौ", "kau"],
  ["kam", "कं", "kaṃ"],
  ["kah", "कः", "kaḥ"],
  ["k-candra", "कँ", "ka̐"],
  ["k-virama", "क्", "k"],
  ["ru", "रु", "ru"],
  ["ruu", "रू", "rū"],
  ["rr", "रृ", "rṛ"],
  ["hr", "हृ", "hṛ"],
  ["hrr", "हॄ", "hṝ"],
  ["naa", "ना", "nā"],
  ["gu", "गु", "gu"],
  ["bhyo", "भ्यो", "bhyo"],
  ["kraa", "क्रा", "krā"],
]);

const numeralItems = letters("akshara", [
  ["0", "०", "0"],
  ["1", "१", "1"],
  ["2", "२", "2"],
  ["3", "३", "3"],
  ["4", "४", "4"],
  ["5", "५", "5"],
  ["6", "६", "6"],
  ["7", "७", "7"],
  ["8", "८", "8"],
  ["9", "९", "9"],
  ["danda", "।", "|", "daṇḍa (end of a sentence or mid-verse)"],
  ["double-danda", "॥", "||", "double daṇḍa (end of a verse)"],
  ["avagraha", "ऽ", "'", "avagraha (elided vowel)"],
]);

const clusterItems = letters(
  "conjunct",
  libraryClusterItems().map((item) => [item.id, item.dev, item.iast]),
);

function deck(
  id: string,
  titleEn: string,
  titleIast: string,
  lessonId: string,
  items: QuizDeckItem[],
  kind: QuizDeck["kind"] = "script",
): QuizDeck {
  const units = [...new Set(items.map((item) => item.unit))];
  return { id, titleEn, titleIast, lessonId, kind, units, items };
}

export const scriptDecks: QuizDeck[] = [
  deck(
    "devanagari-how-it-works",
    "How Devanagari works",
    "devanāgarī",
    "devanagari-how-devanagari-works",
    howItWorksItems,
  ),
  deck(
    "devanagari-vowels-consonants",
    "Vowels and consonants",
    "svara-vyañjana",
    "devanagari-vowels-and-consonants",
    vowelConsonantItems,
  ),
  deck(
    "devanagari-vowel-marks",
    "Vowel marks",
    "mātrā",
    "devanagari-vowel-marks",
    vowelMarkItems,
  ),
  deck(
    "devanagari-clusters",
    "Consonant clusters",
    "saṃyuktākṣara",
    "devanagari-consonant-clusters",
    clusterItems,
  ),
  deck(
    "devanagari-numerals-punctuation",
    "Numerals and punctuation",
    "aṅka-virāma",
    "devanagari-numerals-and-punctuation",
    numeralItems,
  ),
  deck(
    "nominals-rama-a-stems",
    "Masculine rāma",
    "rāma",
    "nominals-a-stems",
    ramaItems,
    "grammar",
  ),
];
