import { group, word } from "../lib/span";
import type { Chapter } from "../types";

const translation =
  "I meditate upon Gāyatrī Devi — whose faces shine with the hues of pearl, coral, gold, sapphire, and crystal; who has three eyes; who wears a gem-studded crown adorned with the moon; who embodies the essence of all tattvas and varṇas; who holds the gestures of boon and fearlessness, the goad and the noose; who is adorned with pure ornaments; who bears the conch and discus and the twin lotuses in her hands.";

export const dhyanam: Chapter = {
  id: "dhyanam",
  titleDev: "ध्यानम्",
  titleIast: "dhyānam",
  titleEn: "Dhyāna",
  status: "ready",
  translation,
  glossary: [
    { term: "muktā", meaning: "pearl" },
    { term: "vidruma", meaning: "coral" },
    { term: "hēma", meaning: "gold" },
    { term: "nīla", meaning: "dark blue, sapphire" },
    { term: "dhavala", meaning: "white" },
    { term: "chāyaiḥ", meaning: "with tints/hues" },
    { term: "mukhaiḥ", meaning: "with faces" },
    {
      term: "tri-akṣaṇaiḥ",
      meaning: "three-eyed (each face having three eyes)",
    },
    { term: "yuktām", meaning: "adorned, attended" },
    { term: "indu-ni-baddha", meaning: "fastened with the moon" },
    { term: "ratna-makuṭa-anta", meaning: "jewel diadem crested at top" },
    { term: "tattvārtha", meaning: "the meaning of ultimate Reality" },
    { term: "varṇa-ātmikām", meaning: "whose nature is the sacred letters" },
    { term: "gāyatrīm", meaning: "Gāyatrī" },
    { term: "varadā", meaning: "boon-bestowing" },
    { term: "abhaya", meaning: "fear-dispelling" },
    { term: "aṅkuśa", meaning: "goad" },
    { term: "kaśā", meaning: "whip" },
    {
      term: "śubhra-aṅga-pāla-aṅgadām",
      meaning: "bright body-protecting ornaments",
    },
    { term: "śaṅkham", meaning: "conch" },
    { term: "chakram", meaning: "discus" },
    { term: "aravinda-yugalam", meaning: "pair of lotuses" },
    { term: "hastaiḥ", meaning: "by/in the hands" },
    { term: "vahantīm", meaning: "bearing, carrying" },
    { term: "bhajē", meaning: "I adore" },
  ],
  root: group("dh-verse", "verse", translation, [
    group(
      "dh-pada-1",
      "sentence",
      "whose faces shine with the hues of pearl, coral, gold, sapphire, and crystal; who has three eyes",
      [
        word(
          "dh-muktavidruma",
          "",
          [
            ["मु", "mu"],
            ["क्ता", "ktā"],
            ["वि", "vi"],
            ["द्रु", "dru"],
            ["म", "ma"],
            ["हे", "he"],
            ["म", "ma"],
            ["नी", "nī"],
            ["ल", "la"],
            ["ध", "dha"],
            ["व", "va"],
            ["ल", "la"],
            ["च्छा", "cchā"],
            ["यै", "yai"],
            ["र्मु", "rmu"],
            ["खै", "khai"],
            ["स्त्र्य", "strya"],
            ["क्ष", "kṣa"],
            ["णैः", "ṇaiḥ"],
          ],
          { trailing: " ।", lineBreakAfter: true },
        ),
      ],
    ),
    group(
      "dh-pada-2",
      "sentence",
      "who wears a gem-studded crown adorned with the moon; who embodies the essence of all tattvas and varṇas",
      [
        word("dh-yuktam", "adorned, attended", [
          ["यु", "yu"],
          ["क्ताम्", "ktām"],
        ]),
        word("dh-indunibaddharatnamakutam", "", [
          ["इन्", "in"],
          ["दु", "du"],
          ["नि", "ni"],
          ["ब", "ba"],
          ["द्ध", "ddha"],
          ["र", "ra"],
          ["त्न", "tna"],
          ["म", "ma"],
          ["कु", "ku"],
          ["टाम्", "ṭām"],
        ]),
        word(
          "dh-tattvarthavarnatmikam",
          "",
          [
            ["तत्", "tat"],
            ["त्वार्", "tvār"],
            ["थ", "tha"],
            ["व", "va"],
            ["र्णा", "rṇā"],
            ["त्मि", "tmi"],
            ["का", "kā"],
            ["म्", "m"],
          ],
          { trailing: " ।", lineBreakAfter: true },
        ),
      ],
    ),
    group(
      "dh-pada-3",
      "sentence",
      "I meditate upon Gāyatrī Devi — who holds the gestures of boon and fearlessness, the goad and the noose; who is adorned with pure ornaments",
      [
        word("dh-gayatrim", "Gāyatrī", [
          ["गा", "gā"],
          ["य", "ya"],
          ["त्रीं", "trīṃ"],
        ]),
        word(
          "dh-varadabhayankusa",
          "",
          [
            ["व", "va"],
            ["र", "ra"],
            ["दा", "dā"],
            ["भ", "bha"],
            ["या", "yā"],
            ["ङ्कु", "ṅku"],
            ["श", "śa"],
            ["क", "ka"],
            ["शा", "śā"],
            ["शु", "śu"],
            ["भ्रा", "bhrā"],
            ["ङ्ग", "ṅga"],
            ["पा", "pā"],
            ["ला", "lā"],
            ["ङ्ग", "ṅga"],
            ["दा", "dā"],
            ["म्", "m"],
          ],
          { trailing: " ।", lineBreakAfter: true },
        ),
      ],
    ),
    group(
      "dh-pada-4",
      "sentence",
      "who bears the conch and discus and the twin lotuses in her hands",
      [
        word("dh-sankham", "conch", [
          ["श", "śa"],
          ["ङ्खं", "ṅkhaṃ"],
        ]),
        word("dh-cakram", "discus", [
          ["च", "ca"],
          ["क्रं", "kraṃ"],
        ]),
        word("dh-dhararavindayugalam", "", [
          ["ध", "dha"],
          ["रा", "rā"],
          ["र", "ra"],
          ["वि", "vi"],
          ["न्द", "nda"],
          ["यु", "yu"],
          ["ग", "ga"],
          ["लं", "laṃ"],
        ]),
        word("dh-hastairvahantim", "", [
          ["ह", "ha"],
          ["स्तै", "stai"],
          ["र्व", "rva"],
          ["ह", "ha"],
          ["न्तीं", "ntīṃ"],
        ]),
        word(
          "dh-bhaje",
          "I adore",
          [
            ["भ", "bha"],
            ["जे", "je"],
          ],
          { trailing: " ॥" },
        ),
      ],
    ),
  ]),
};
