#!/usr/bin/env python3
"""Nikh-style pada rows for verses 7–46 (Param saṃhitā, join slices).

Each row: (pada_dev, slice_dev, after, meaning)
Run: python3 scripts/ddv-nikh-padas.py          # join-test
     python3 scripts/ddv-nikh-padas.py apply    # write md + lift
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEXT = ROOT / "docs" / "ddv" / "text"

spec = importlib.util.spec_from_file_location("ddv_iast", ROOT / "scripts" / "ddv-iast.py")
iast = importlib.util.module_from_spec(spec)
spec.loader.exec_module(iast)

chk_spec = importlib.util.spec_from_file_location("check_ddv_text", ROOT / "scripts" / "check-ddv-text.py")
chk = importlib.util.module_from_spec(chk_spec)
chk_spec.loader.exec_module(chk)

AFTER = chk.AFTER

# pada_dev, slice_dev, after, meaning
PADAS: dict[int, list[tuple[str, str, str, str]]] = {
    7: [
        ("छाया", "छायाऽ", "join", "reflection"),
        ("अहङ्कारयोः", "हङ्कारयो", "join", "and the ego"),
        ("ऐक्यं", "रैक्यं", "space", "identity"),
        ("तप्त", "तप्ता", "join", "heated"),
        ("अयः", "यः", "join", "iron"),
        ("पिण्डवत्", "पिण्डवन्", "join", "like a ball"),
        ("मतम्", "मतम्", "danda", "is held (by the wise)"),
        ("तत्", "तद", "join", "that"),
        ("अहङ्कार", "हङ्कार", "join", "ego"),
        ("तादात्म्यात्", "तादात्म्याद्", "join", "from identification"),
        ("देहः", "देहश्", "join", "the body"),
        ("चेतनताम्", "चेतनताम", "join", "sentiency"),
        ("अगात्", "गात्", "ddanda", "has attained"),
    ],
    8: [
        ("अहङ्कारस्य", "अहङ्कारस्य", "space", "of the ego"),
        ("तादात्म्यं", "तादात्म्यं", "space", "identification"),
        ("चित्", "चिच्", "join", "Consciousness"),
        ("छाया", "छाया", "join", "reflection"),
        ("देह", "देह", "join", "the body"),
        ("साक्षिभिः", "साक्षिभिः", "danda", "and the Witness"),
        ("सहजं", "सहजं", "space", "natural"),
        ("कर्म", "कर्म", "join", "of karma"),
        ("जम्", "जं", "space", "born"),
        ("भ्रान्ति", "भ्रान्ति", "join", "of error"),
        ("जन्यम्", "जन्यं", "space", "born"),
        ("च", "च", "space", "and"),
        ("त्रि", "त्रि", "join", "three"),
        ("विधम्", "विधं", "space", "kinds"),
        ("क्रमात्", "क्रमात्", "ddanda", "in that order"),
    ],
    9: [
        ("सम्बन्धिनोः", "सम्बन्धिनोः", "space", "of the two that are related"),
        ("सतोः", "सतोर्", "join", "of those taken as real"),
        ("न", "ना", "join", "not"),
        ("अस्ति", "स्ति", "space", "there is"),
        ("निवृत्तिः", "निवृत्तिः", "space", "cessation"),
        ("सहजस्य", "सहजस्य", "space", "of the natural (identification)"),
        ("तु", "तु", "danda", "but"),
        ("कर्म", "कर्म", "join", "of karma"),
        ("क्षयात्", "क्षयात्", "space", "from the wearing-out"),
        ("प्रबोधात्", "प्रबोधाच्", "join", "from awakening"),
        ("च", "च", "space", "and"),
        ("निवर्तेते", "निवर्तेते", "space", "the two cease"),
        ("क्रमात्", "क्रमादु", "join", "in order"),
        ("उभे", "भे", "ddanda", "both"),
    ],
    10: [
        ("अहङ्कार", "अहङ्कार", "join", "ego"),
        ("लये", "लये", "space", "on the dissolution"),
        ("सुप्तौ", "सुप्तौ", "space", "in deep sleep"),
        ("भवेत्", "भवेद्", "join", "becomes"),
        ("देहः", "देहोऽ", "join", "the body"),
        ("अपि", "प्य", "join", "also"),
        ("अचेतनः", "चेतनः", "danda", "unconscious"),
        ("अहङ्कार", "अहङ्कार", "join", "ego"),
        ("विकास", "विकासा", "join", "expansion"),
        ("अर्धः", "र्धः", "space", "half"),
        ("स्वप्नः", "स्वप्नः", "space", "dream"),
        ("सर्वः", "सर्वस्", "join", "the full (expansion)"),
        ("तु", "तु", "space", "but"),
        ("जागरः", "जागरः", "ddanda", "waking"),
    ],
    11: [
        ("अन्तःकरण", "अन्तःकरण", "join", "inner organ"),
        ("वृत्तिः", "वृत्तिश्", "join", "a modification"),
        ("च", "च", "space", "and"),
        ("चिति", "चिति", "join", "Consciousness"),
        ("छाया", "च्छायै", "join", "reflection"),
        ("ऐक्यम्", "क्यमा", "join", "identity"),
        ("आगता", "गता", "danda", "having attained"),
        ("वासनाः", "वासनाः", "space", "impressions"),
        ("कल्पयेत्", "कल्पयेत्", "space", "it imagines"),
        ("स्वप्ने", "स्वप्ने", "space", "in dream"),
        ("बोधे", "बोधेऽ", "join", "in waking"),
        ("अक्षैः", "क्षैर्", "join", "through the senses"),
        ("विषयान्", "विषयान्", "space", "objects"),
        ("बहिः", "बहिः", "ddanda", "outside"),
    ],
    12: [
        ("मनस्", "मनोऽ", "join", "mind"),
        ("अहङ्कृत्युपादानम्", "हङ्कृत्युपादानं", "space", "having ego as material"),
        ("लिङ्गम्", "लिङ्गमे", "join", "the subtle body"),
        ("एकं", "कं", "space", "one"),
        ("जड", "जडा", "join", "insentient"),
        ("आत्मकम्", "त्मकम्", "danda", "of the nature of"),
        ("अवस्था", "अवस्था", "join", "states"),
        ("त्रयम्", "त्रयम", "join", "three"),
        ("अन्वेति", "न्वेति", "space", "it follows"),
        ("जायते", "जायते", "space", "is born"),
        ("म्रियते", "म्रियते", "space", "dies"),
        ("तथा", "तथा", "ddanda", "likewise"),
    ],
    13: [
        ("शक्ति", "शक्ति", "join", "powers"),
        ("द्वयम्", "द्वयं", "space", "a pair"),
        ("हि", "हि", "space", "indeed"),
        ("मायायाः", "मायाया", "space", "of Māyā"),
        ("विक्षेप", "विक्षेपा", "join", "projecting"),
        ("आवृति", "वृति", "join", "veiling"),
        ("रूपकम्", "रूपकम्", "danda", "of the form of"),
        ("विक्षेप", "विक्षेप", "join", "projecting"),
        ("शक्तिः", "शक्तिर्", "join", "power"),
        ("लिङ्गादि", "लिङ्गादि", "space", "from the subtle body onward"),
        ("ब्रह्माण्ड", "ब्रह्माण्डा", "join", "the cosmic egg"),
        ("अन्तम्", "न्तं", "space", "up to"),
        ("जगत्", "जगत्", "space", "the world"),
        ("सृजेत्", "सृजेत्", "ddanda", "creates"),
    ],
    14: [
        ("सृष्टिः", "सृष्टिर्", "join", "creation"),
        ("नाम", "नाम", "space", "is called"),
        ("ब्रह्म", "ब्रह्म", "join", "Brahman"),
        ("रूपे", "रूपे", "space", "in that which has the nature of"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्द", "नन्द", "join", "Bliss"),
        ("वस्तुनि", "वस्तुनि", "danda", "in the entity"),
        ("अब्धौ", "अब्धौ", "space", "in the ocean"),
        ("फेन", "फेना", "join", "foam"),
        ("आदिवत्", "दिवत्", "space", "and so on, like"),
        ("सर्व", "सर्व", "join", "all"),
        ("नाम", "नाम", "join", "names"),
        ("रूप", "रूप", "join", "and forms"),
        ("प्रसारणा", "प्रसारणा", "ddanda", "the spreading"),
    ],
    15: [
        ("अन्तर्", "अन्तर्", "join", "within"),
        ("दृक्", "दृग्", "join", "seer"),
        ("दृश्ययोः", "दृश्ययोर्", "join", "and seen"),
        ("भेदं", "भेदं", "space", "the distinction"),
        ("बहिः", "बहिश्", "join", "outwardly"),
        ("च", "च", "space", "and"),
        ("ब्रह्म", "ब्रह्म", "join", "Brahman"),
        ("सर्गयोः", "सर्गयोः", "danda", "and creation"),
        ("आवृणोति", "आवृणोत्य", "join", "conceals"),
        ("अपरा", "परा", "space", "the other"),
        ("शक्तिः", "शक्तिः", "space", "power"),
        ("सा", "सा", "space", "that"),
        ("संसारस्य", "संसारस्य", "space", "of saṃsāra"),
        ("कारणम्", "कारणम्", "ddanda", "the cause"),
    ],
    16: [
        ("साक्षिणः", "साक्षिणः", "space", "of the Witness"),
        ("पुरतः", "पुरतो", "space", "in front"),
        ("भाति", "भाति", "space", "appears"),
        ("लिङ्गं", "लिङ्गं", "space", "the subtle body"),
        ("देहेन", "देहेन", "space", "with the (gross) body"),
        ("संयुतम्", "संयुतम्", "danda", "joined"),
        ("चिति", "चिति", "join", "Consciousness"),
        ("छाया", "च्छाया", "space", "the reflection"),
        ("समावेशात्", "समावेशाज्", "join", "from its entry"),
        ("जीवः", "जीवः", "space", "the living self"),
        ("स्यात्", "स्याद्", "join", "becomes"),
        ("व्यावहारिकः", "व्यावहारिकः", "ddanda", "empirical"),
    ],
    17: [
        ("अस्य", "अस्य", "space", "of this"),
        ("जीवत्वम्", "जीवत्वमा", "join", "jīva-hood"),
        ("आरोपात्", "रोपात्", "space", "from superimposition"),
        ("साक्षिणि", "साक्षिण्य", "join", "in the Witness"),
        ("अपि", "प्य", "join", "even"),
        ("अवभासते", "वभासते", "danda", "it appears"),
        ("आवृतौ", "आवृतौ", "space", "when the veiling"),
        ("तु", "तु", "space", "but"),
        ("विनष्टायां", "विनष्टायां", "space", "has been destroyed"),
        ("भेदे", "भेदे", "space", "when the distinction"),
        ("भाते", "भातेऽ", "join", "having shone"),
        ("अपयाति", "पयाति", "space", "goes away"),
        ("तत्", "तत्", "ddanda", "that"),
    ],
    18: [
        ("तथा", "तथा", "space", "in the same way"),
        ("सर्ग", "सर्ग", "join", "creation"),
        ("ब्रह्मणोः", "ब्रह्मणोश्", "join", "and Brahman"),
        ("च", "च", "space", "and"),
        ("भेदम्", "भेदमा", "join", "the distinction"),
        ("आवृत्य", "वृत्य", "space", "having concealed"),
        ("तिष्ठति", "तिष्ठति", "danda", "it remains"),
        ("या", "या", "space", "which"),
        ("शक्तिः", "शक्तिस्", "join", "power"),
        ("तत्", "तद्", "join", "its"),
        ("वशात्", "वशाद्", "join", "by the force"),
        ("ब्रह्म", "ब्रह्म", "space", "Brahman"),
        ("विकृतत्वेन", "विकृतत्वेन", "space", "as modified"),
        ("भासते", "भासते", "ddanda", "appears"),
    ],
    19: [
        ("अत्र", "अत्रा", "join", "here"),
        ("अपि", "प्या", "join", "too"),
        ("आवृति", "वृति", "join", "of the veiling"),
        ("नाशेन", "नाशेन", "space", "by destruction"),
        ("विभाति", "विभाति", "space", "shines"),
        ("ब्रह्म", "ब्रह्म", "join", "Brahman"),
        ("सर्गयोः", "सर्गयोः", "danda", "and creation"),
        ("भेदः", "भेदस्", "join", "their distinction"),
        ("तयोः", "तयोर्", "join", "of those two"),
        ("विकारः", "विकारः", "space", "modification"),
        ("स्यात्", "स्यात्", "space", "would be"),
        ("सर्गे", "सर्गे", "space", "in creation"),
        ("न", "न", "space", "not"),
        ("ब्रह्मणि", "ब्रह्मणि", "space", "in Brahman"),
        ("क्वचित्", "क्वचित्", "ddanda", "anywhere"),
    ],
    20: [
        ("अस्ति", "अस्ति", "space", "it exists"),
        ("भाति", "भाति", "space", "it shines"),
        ("प्रियं", "प्रियं", "space", "it is dear"),
        ("रूपं", "रूपं", "space", "form"),
        ("नाम", "नाम", "space", "name"),
        ("च", "चे", "join", "and"),
        ("इति", "त्यं", "join", "thus"),
        ("अंश", "श", "join", "aspects"),
        ("पञ्चकम्", "पञ्चकम्", "danda", "a group of five"),
        ("आद्य", "आद्य", "join", "the first"),
        ("त्रयम्", "त्रयं", "space", "three"),
        ("ब्रह्म", "ब्रह्म", "join", "Brahman"),
        ("रूपम्", "रूपं", "space", "are the nature of"),
        ("जगत्", "जगद्", "join", "the world"),
        ("रूपम्", "रूपं", "space", "the nature of"),
        ("ततः", "ततो", "space", "then"),
        ("द्वयम्", "द्वयम्", "ddanda", "the two"),
    ],
    21: [
        ("ख", "ख", "join", "ether"),
        ("वायु", "वाय्व", "join", "air"),
        ("अग्नि", "ग्नि", "join", "fire"),
        ("जलोर्वीषु", "जलोर्वीषु", "space", "water and earth"),
        ("देव", "देव", "join", "gods"),
        ("तिर्यञ्च्", "तिर्यङ्", "join", "animals"),
        ("नरादिषु", "नरादिषु", "danda", "humans, etc."),
        ("अभिन्नाः", "अभिन्नाः", "space", "undivided"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्दाः", "नन्दाः", "space", "Bliss"),
        ("भिद्येते", "भिद्येते", "space", "the two differ"),
        ("रूप", "रूप", "join", "form"),
        ("नामनी", "नामनी", "ddanda", "and name"),
    ],
    22: [
        ("उपेक्ष्य", "उपेक्ष्य", "space", "having disregarded"),
        ("नाम", "नाम", "join", "name"),
        ("रूपे", "रूपे", "space", "and form"),
        ("द्वे", "द्वे", "space", "the two"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्द", "नन्द", "join", "Bliss"),
        ("तत्परः", "तत्परः", "danda", "intent on"),
        ("समाधिं", "समाधिं", "space", "samādhi"),
        ("सर्वदा", "सर्वदा", "space", "always"),
        ("कुर्यात्", "कुर्याद्", "join", "one should practise"),
        ("हृदये", "धृदये", "space", "in the heart"),
        ("वा", "वाऽ", "join", "or"),
        ("अथवा", "थवा", "space", "or else"),
        ("बहिः", "बहिः", "ddanda", "outside"),
    ],
    23: [
        ("सविकल्पः", "सविकल्पो", "space", "with distinction"),
        ("निर्विकल्पः", "निर्विकल्पः", "space", "without distinction"),
        ("समाधिः", "समाधिर्", "join", "samādhi"),
        ("द्विविधः", "द्विविधो", "space", "is of two kinds"),
        ("हृदि", "हृदि", "danda", "in the heart"),
        ("दृश्य", "दृश्य", "join", "the seen"),
        ("शब्द", "शब्दा", "join", "word"),
        ("अनुविद्धेन", "नुविद्धेन", "space", "associated with"),
        ("सविकल्पः", "सविकल्पः", "space", "savikalpa"),
        ("पुनः", "पुनर्", "join", "again"),
        ("द्विधा", "द्विधा", "ddanda", "twofold"),
    ],
    24: [
        ("काम", "कामा", "join", "desires"),
        ("आद्याः", "द्याश्", "join", "and the rest"),
        ("चित्त", "चित्त", "join", "in the mind"),
        ("गाः", "गा", "space", "occurring"),
        ("दृश्याः", "दृश्यास्", "join", "are the seen"),
        ("तत्", "तत्", "join", "their"),
        ("साक्षित्वेन", "साक्षित्वेन", "space", "as Witness"),
        ("चेतनम्", "चेतनम्", "danda", "Consciousness"),
        ("ध्यायेत्", "ध्यायेद्", "join", "one should meditate"),
        ("दृश्य", "दृश्या", "join", "the seen"),
        ("अनुविद्धः", "नुविद्धोऽ", "join", "associated with"),
        ("अयं", "यं", "space", "this"),
        ("समाधिः", "समाधिः", "space", "samādhi"),
        ("सविकल्पकः", "सविकल्पकः", "ddanda", "with distinction"),
    ],
    25: [
        ("असङ्गः", "असङ्गः", "space", "unattached"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्दः", "नन्दः", "space", "Bliss"),
        ("स्व", "स्व", "join", "self"),
        ("प्रभः", "प्रभो", "space", "luminous"),
        ("द्वैत", "द्वैत", "join", "duality"),
        ("वर्जितः", "वर्जितः", "danda", "free from"),
        ("अस्मि", "अस्मी", "join", "I am"),
        ("इति", "ति", "space", "thus"),
        ("शब्द", "शब्द", "join", "words"),
        ("विद्धः", "विद्धोऽ", "join", "associated with"),
        ("अयं", "यं", "space", "this"),
        ("समाधिः", "समाधिः", "space", "samādhi"),
        ("सविकल्पकः", "सविकल्पकः", "ddanda", "with distinction"),
    ],
    26: [
        ("स्व", "स्वा", "join", "one’s own"),
        ("अनुभूति", "नुभूति", "join", "experience"),
        ("रस", "रसा", "join", "taste"),
        ("आवेशात्", "वेशाद्", "join", "from absorption"),
        ("दृश्य", "दृश्य", "join", "seen"),
        ("शब्दौ", "शब्दावु", "join", "and word"),
        ("उपेक्ष्य", "पेक्ष्य", "space", "having disregarded"),
        ("तु", "तु", "danda", "but"),
        ("निर्विकल्पः", "निर्विकल्पः", "space", "without distinction"),
        ("समाधिः", "समाधिः", "space", "samādhi"),
        ("स्यात्", "स्यान्", "join", "would be"),
        ("निवात", "निवात", "join", "windless"),
        ("स्थित", "स्थित", "join", "standing"),
        ("दीपवत्", "दीपवत्", "ddanda", "like a lamp"),
    ],
    27: [
        ("हृदि", "हृदी", "join", "in the heart"),
        ("इव", "व", "space", "as"),
        ("बाह्य", "बाह्य", "join", "outer"),
        ("देशे", "देशेऽ", "join", "place"),
        ("अपि", "पि", "space", "even"),
        ("यस्मिन्", "यस्मिन्", "space", "in whichever"),
        ("कस्मिंश्च", "कस्मिंश्च", "space", "and in whatever"),
        ("वस्तुनि", "वस्तुनि", "danda", "thing"),
        ("समाधिः", "समाधिरा", "join", "samādhi"),
        ("आद्यः", "द्यः", "space", "the first"),
        ("सत्", "सन्", "join", "Existence"),
        ("मात्रात्", "मात्रान्", "join", "from … alone"),
        ("नाम", "नाम", "join", "name"),
        ("रूप", "रूप", "join", "and form"),
        ("पृथक्", "पृथक्", "join", "separating"),
        ("कृतिः", "कृतिः", "ddanda", "the act of"),
    ],
    28: [
        ("अखण्ड", "अखण्डै", "join", "undivided"),
        ("एकरसम्", "करसं", "space", "of one taste"),
        ("वस्तु", "वस्तु", "space", "the Reality"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्द", "नन्द", "join", "Bliss"),
        ("लक्षणम्", "लक्षणम्", "danda", "whose mark is"),
        ("इति", "इत्य", "join", "thus"),
        ("अविच्छिन्न", "विच्छिन्न", "join", "uninterrupted"),
        ("चिन्ता", "चिन्ते", "join", "thought"),
        ("इयं", "यं", "space", "this"),
        ("समाधिः", "समाधिर्", "join", "samādhi"),
        ("मध्यमः", "मध्यमो", "space", "the middle"),
        ("भवेत्", "भवेत्", "ddanda", "would be"),
    ],
    29: [
        ("स्तब्धी", "स्तब्धी", "join", "stillness"),
        ("भावः", "भावो", "space", "a state of"),
        ("रस", "रसा", "join", "rasa"),
        ("आस्वादात्", "स्वादात्", "join", "from tasting"),
        ("तृतीयः", "तृतीयः", "space", "the third"),
        ("पूर्ववत्", "पूर्ववन्", "join", "like the previous"),
        ("मतः", "मतः", "danda", "is held"),
        ("एतैः", "एतैः", "space", "by these"),
        ("समाधिभिः", "समाधिभिः", "space", "samādhis"),
        ("षड्भिः", "षड्भिर्", "join", "six"),
        ("नयेत्", "नयेत्", "space", "one should lead"),
        ("कालं", "कालं", "space", "time"),
        ("निरन्तरम्", "निरन्तरम्", "ddanda", "without interruption"),
    ],
    30: [
        ("देह", "देहा", "join", "the body"),
        ("अभिमाने", "भिमाने", "space", "when identification with"),
        ("गलिते", "गलिते", "space", "has melted"),
        ("विज्ञाते", "विज्ञाते", "space", "when known"),
        ("परम", "परमा", "join", "supreme"),
        ("आत्मनि", "त्मनि", "danda", "Self"),
        ("यत्र", "यत्र", "space", "wherever"),
        ("यत्र", "यत्र", "space", "wherever"),
        ("मनः", "मनो", "space", "the mind"),
        ("याति", "याति", "space", "goes"),
        ("तत्र", "तत्र", "space", "there"),
        ("तत्र", "तत्र", "space", "there"),
        ("समाधयः", "समाधयः", "ddanda", "samādhis"),
    ],
    31: [
        ("भिद्यते", "भिद्यते", "space", "is split"),
        ("हृदय", "हृदय", "join", "of the heart"),
        ("ग्रन्थिः", "ग्रन्थिश्", "join", "the knot"),
        ("छिद्यन्ते", "छिद्यन्ते", "space", "are cut"),
        ("सर्व", "सर्व", "join", "all"),
        ("संशयाः", "संशयाः", "danda", "doubts"),
        ("क्षीयन्ते", "क्षीयन्ते", "space", "wear away"),
        ("च", "चा", "join", "and"),
        ("अस्य", "स्य", "space", "his"),
        ("कर्माणि", "कर्माणि", "space", "karmas"),
        ("तस्मिन्", "तस्मिन्", "space", "in that"),
        ("दृष्टे", "दृष्टे", "space", "when seen"),
        ("पर", "परा", "join", "high"),
        ("अवरे", "वरे", "ddanda", "and low"),
    ],
    32: [
        ("अवच्छिन्नः", "अवच्छिन्नश्", "join", "the limited one"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आभासः", "भासस्", "join", "the reflection"),
        ("तृतीयः", "तृतीयः", "space", "a third"),
        ("स्वप्न", "स्वप्न", "join", "in dream"),
        ("कल्पितः", "कल्पितः", "danda", "imagined"),
        ("विज्ञेयः", "विज्ञेयस्", "join", "is to be known"),
        ("त्रिविधः", "त्रिविधो", "space", "threefold"),
        ("जीवः", "जीवस्", "join", "the jīva"),
        ("तत्र", "तत्रा", "join", "of them"),
        ("आद्यः", "द्यः", "space", "the first"),
        ("पारमार्थिकः", "पारमार्थिकः", "ddanda", "is the absolute"),
    ],
    33: [
        ("अवच्छेदः", "अवच्छेदः", "space", "limitation"),
        ("कल्पितः", "कल्पितः", "space", "is imagined"),
        ("स्यात्", "स्याद", "join", "would be"),
        ("अवच्छेद्यं", "वच्छेद्यं", "space", "that which is limited"),
        ("तु", "तु", "space", "but"),
        ("वास्तवम्", "वास्तवम्", "danda", "is real"),
        ("तस्मिन्", "तस्मिन्", "space", "on that"),
        ("जीवत्वम्", "जीवत्वमा", "join", "jīva-hood"),
        ("आरोपात्", "रोपाद्", "join", "from superimposition"),
        ("ब्रह्मत्वं", "ब्रह्मत्वं", "space", "Brahman-hood"),
        ("तु", "तु", "space", "but"),
        ("स्वभावतः", "स्वभावतः", "ddanda", "by its own nature"),
    ],
    34: [
        ("अवच्छिन्नस्य", "अवच्छिन्नस्य", "space", "of the limited"),
        ("जीवस्य", "जीवस्य", "space", "jīva"),
        ("पूर्णेन", "पूर्णेन", "space", "with the full"),
        ("ब्रह्मणः", "ब्रह्मणै", "join", "with Brahman"),
        ("एकताम्", "कताम्", "danda", "identity"),
        ("तत्", "तत्", "join", "that"),
        ("त्वम्", "त्वम", "join", "thou"),
        ("अस्यादि", "स्यादि", "join", "art — and so on"),
        ("वाक्यानि", "वाक्यानि", "space", "statements"),
        ("जगुः", "जगुर्", "join", "have declared"),
        ("न", "ने", "join", "not"),
        ("इतर", "तर", "join", "the other"),
        ("जीवयोः", "जीवयोः", "ddanda", "two jīvas"),
    ],
    35: [
        ("ब्रह्मणि", "ब्रह्मण्य", "join", "in Brahman"),
        ("अवस्थिता", "वस्थिता", "space", "established"),
        ("माया", "माया", "space", "Māyā"),
        ("विक्षेप", "विक्षेपा", "join", "projecting"),
        ("आवृति", "वृति", "join", "veiling"),
        ("रूपिणी", "रूपिणी", "danda", "of the nature of"),
        ("आवृत्य", "आवृत्या", "join", "having covered"),
        ("अखण्डतां", "खण्डतां", "space", "undividedness"),
        ("तस्मिन्", "तस्मिन्", "space", "in that"),
        ("जगत्", "जगज्", "join", "world"),
        ("जीवौ", "जीवौ", "space", "and jīva"),
        ("प्रकल्पयेत्", "प्रकल्पयेत्", "ddanda", "she imagines"),
    ],
    36: [
        ("जीवः", "जीवो", "space", "the jīva"),
        ("धी", "धी", "join", "intellect"),
        ("स्थ", "स्थ", "join", "standing in"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आभासः", "भासो", "space", "the reflection"),
        ("भवेत्", "भवेद्", "join", "would be"),
        ("भोक्ता", "भोक्ता", "space", "the enjoyer"),
        ("हि", "हि", "space", "for"),
        ("कर्म", "कर्म", "join", "karma"),
        ("कृत्", "कृत्", "danda", "the doer of"),
        ("भोग्य", "भोग्य", "join", "the enjoyed"),
        ("रूपम्", "रूपमि", "join", "of the nature of"),
        ("इदं", "दं", "space", "this"),
        ("सर्वं", "सर्वं", "space", "all"),
        ("जगत्", "जगत्", "space", "the world"),
        ("स्यात्", "स्याद्", "join", "would be"),
        ("भूत", "भूत", "join", "elements"),
        ("भौतिकम्", "भौतिकम्", "ddanda", "and made of elements"),
    ],
    37: [
        ("अनादि", "अनादि", "join", "beginningless"),
        ("कालम्", "कालमा", "join", "time"),
        ("आरभ्य", "रभ्य", "space", "beginning from"),
        ("मोक्षात्", "मोक्षात्", "space", "from liberation"),
        ("पूर्वम्", "पूर्वमि", "join", "before it"),
        ("इदं", "दं", "space", "this"),
        ("द्वयम्", "द्वयम्", "danda", "pair"),
        ("व्यवहारे", "व्यवहारे", "space", "in empirical dealing"),
        ("स्थितं", "स्थितं", "space", "stands"),
        ("तस्मात्", "तस्मादु", "join", "therefore"),
        ("उभयं", "भयं", "space", "both"),
        ("व्यावहारिकम्", "व्यावहारिकम्", "ddanda", "are empirical"),
    ],
    38: [
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आभास", "भास", "join", "reflection"),
        ("स्थिता", "स्थिता", "space", "seated in"),
        ("निद्रा", "निद्रा", "space", "sleep"),
        ("विक्षेप", "विक्षेपा", "join", "projecting"),
        ("आवृति", "वृति", "join", "veiling"),
        ("रूपिणी", "रूपिणी", "danda", "of the nature of"),
        ("आवृत्य", "आवृत्य", "space", "having covered"),
        ("जीव", "जीव", "join", "jīva"),
        ("जगती", "जगती", "space", "and world"),
        ("पूर्वे", "पूर्वे", "space", "the previous"),
        ("नूत्ने", "नूत्ने", "space", "new ones"),
        ("तु", "तु", "space", "but"),
        ("कल्पयेत्", "कल्पयेत्", "ddanda", "it imagines"),
    ],
    39: [
        ("प्रतीति", "प्रतीति", "join", "appearing"),
        ("काल", "काल", "space", "the time of"),
        ("एव", "एवै", "join", "only"),
        ("एते", "ते", "space", "these two"),
        ("स्थितत्वात्", "स्थितत्वात्", "space", "because they stood (then)"),
        ("प्रातिभासिके", "प्रातिभासिके", "danda", "in the apparent (order)"),
        ("न", "न", "space", "not"),
        ("हि", "हि", "space", "indeed"),
        ("स्वप्न", "स्वप्न", "join", "from dream"),
        ("प्रबुद्धस्य", "प्रबुद्धस्य", "space", "of one awakened"),
        ("पुनः", "पुनः", "space", "again"),
        ("स्वप्ने", "स्वप्ने", "space", "in dream"),
        ("स्थितिः", "स्थितिस्", "join", "is the standing"),
        ("तयोः", "तयोः", "ddanda", "of those two"),
    ],
    40: [
        ("प्रातिभासिक", "प्रातिभासिक", "join", "apparent"),
        ("जीवः", "जीवो", "space", "the jīva"),
        ("यः", "यस्", "join", "who"),
        ("तत्", "तज्", "join", "that"),
        ("जगत्", "जगत्", "space", "world"),
        ("प्रातिभासिकम्", "प्रातिभासिकम्", "danda", "is apparent"),
        ("वास्तवं", "वास्तवं", "space", "as real"),
        ("मन्यते", "मन्यतेऽ", "join", "thinks"),
        ("अन्यः", "न्यस्", "join", "another"),
        ("तु", "तु", "space", "but"),
        ("मिथ्या", "मिथ्ये", "join", "as false"),
        ("इति", "ति", "space", "thus"),
        ("व्यावहारिकः", "व्यावहारिकः", "ddanda", "the empirical (jīva)"),
    ],
    41: [
        ("व्यावहारिक", "व्यावहारिक", "join", "empirical"),
        ("जीवः", "जीवो", "space", "the jīva"),
        ("यः", "यस्", "join", "who"),
        ("तत्", "तज्", "join", "that"),
        ("जगत्", "जगद्", "join", "world"),
        ("व्यावहारिकम्", "व्यावहारिकम्", "danda", "is empirical"),
        ("सत्यं", "सत्यं", "space", "as true"),
        ("प्रत्येति", "प्रत्येति", "space", "cognizes"),
        ("मिथ्या", "मिथ्ये", "join", "as false"),
        ("इति", "ति", "space", "thus"),
        ("मन्यते", "मन्यते", "space", "thinks"),
        ("पारमार्थिकः", "पारमार्थिकः", "ddanda", "the absolute (jīva)"),
    ],
    42: [
        ("पारमार्थिक", "पारमार्थिक", "join", "absolute"),
        ("जीवः", "जीवस्", "join", "the jīva"),
        ("तु", "तु", "space", "but"),
        ("ब्रह्म", "ब्रह्मै", "join", "Brahman"),
        ("ऐक्यम्", "क्यं", "space", "identity with"),
        ("पारमार्थिकम्", "पारमार्थिकम्", "danda", "as absolute"),
        ("प्रत्येति", "प्रत्येति", "space", "cognizes"),
        ("वीक्षते", "वीक्षते", "space", "sees"),
        ("न", "ना", "join", "does not"),
        ("अन्यत्", "न्यद्", "join", "another"),
        ("वीक्षते", "वीक्षते", "space", "it sees"),
        ("तु", "त्व", "join", "but"),
        ("अनृत", "नृता", "join", "untruth"),
        ("आत्मना", "त्मना", "ddanda", "as of the nature of"),
    ],
    43: [
        ("माधुर्य", "माधुर्य", "join", "sweetness"),
        ("द्रव", "द्रव", "join", "fluidity"),
        ("शैत्यानि", "शैत्यानि", "space", "and coldness"),
        ("नीर", "नीर", "join", "of water"),
        ("धर्माः", "धर्मास्", "join", "properties"),
        ("तरङ्गके", "तरङ्गके", "danda", "in the wave"),
        ("अनुगम्य", "अनुगम्या", "join", "having inhered"),
        ("अथ", "थ", "space", "then"),
        ("तत्", "तन्", "join", "that"),
        ("निष्ठे", "निष्ठे", "space", "in that which rests on"),
        ("फेने", "फेनेऽ", "join", "in the foam"),
        ("अपि", "प्य", "join", "also"),
        ("अनुगता", "नुगता", "space", "inhere"),
        ("यथा", "यथा", "ddanda", "as"),
    ],
    44: [
        ("साक्षि", "साक्षि", "join", "in the Witness"),
        ("स्थाः", "स्थाः", "space", "standing"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्दाः", "नन्दाः", "space", "Bliss"),
        ("सम्बन्धात्", "सम्बन्धाद्व्", "join", "from relation"),
        ("व्यावहारिके", "यावहारिके", "danda", "in the empirical"),
        ("तत्", "तद्", "join", "that"),
        ("द्वारेण", "द्वारेणा", "join", "through"),
        ("अनुगच्छन्ति", "नुगच्छन्ति", "space", "they follow"),
        ("तथैव", "तथैव", "space", "in the same way"),
        ("प्रातिभासिके", "प्रातिभासिके", "ddanda", "in the apparent"),
    ],
    45: [
        ("लये", "लये", "space", "on dissolution"),
        ("फेनस्य", "फेनस्य", "space", "of the foam"),
        ("तत्", "तद्", "join", "those"),
        ("धर्माः", "धर्मा", "space", "properties of it"),
        ("द्रव", "द्रवा", "join", "fluidity"),
        ("आद्याः", "द्याः", "space", "and the rest"),
        ("स्युः", "स्युस्", "join", "would be"),
        ("तरङ्गके", "तरङ्गके", "danda", "in the wave"),
        ("तस्य", "तस्या", "join", "of that"),
        ("अपि", "पि", "space", "too"),
        ("विलये", "विलये", "space", "on dissolution"),
        ("नीरे", "नीरे", "space", "in the water"),
        ("तिष्ठन्ति", "तिष्ठन्त्ये", "join", "these remain"),
        ("एते", "ते", "space", "these"),
        ("यथा", "यथा", "space", "as"),
        ("पुरा", "पुरा", "ddanda", "before"),
    ],
    46: [
        ("प्रातिभासिक", "प्रातिभासिक", "join", "apparent"),
        ("जीवस्य", "जीवस्य", "space", "of the jīva"),
        ("लये", "लये", "space", "on dissolution"),
        ("स्युः", "स्युर्", "join", "they would be"),
        ("व्यावहारिके", "व्यावहारिके", "danda", "in the empirical"),
        ("तत्", "तल्", "join", "of that"),
        ("लये", "लये", "space", "on the dissolution"),
        ("सत्", "सच्", "join", "Existence"),
        ("चित्", "चिदा", "join", "Consciousness"),
        ("आनन्दाः", "नन्दाः", "space", "Bliss"),
        ("पर्यवस्यन्ति", "पर्यवस्यन्ति", "space", "come to rest"),
        ("साक्षिणि", "साक्षिणि", "ddanda", "in the Witness"),
    ],
}


def samhita_of(n: int) -> str:
    text = (TEXT / f"ddv-{n:02d}.md").read_text(encoding="utf-8")
    fences = dict(re.findall(r"```([a-z_]+)\n(.*?)```", text, flags=re.S))
    return iast.nfc(fences["samhita"].replace("\r\n", "\n").strip("\n"))


def join_dev(rows: list[tuple[str, str, str, str]]) -> str:
    return "".join(sl + AFTER[after][0] for _p, sl, after, _m in rows).strip("\n")


def test_all() -> int:
    rc = 0
    for n in sorted(PADAS):
        want = samhita_of(n)
        got = iast.nfc(join_dev(PADAS[n]))
        if got != want:
            rc = 1
            print(f"FAIL v{n}")
            print(f"  want: {want!r}")
            print(f"  got:  {got!r}")
        else:
            print(f"OK v{n} ({len(PADAS[n])} padas)")
    return rc


def apply() -> int:
    rc = test_all()
    if rc:
        return rc
    for n, rows in PADAS.items():
        path = TEXT / f"ddv-{n:02d}.md"
        text = path.read_text(encoding="utf-8")
        fences = dict(re.findall(r"```([a-z_]+)\n(.*?)```", text, flags=re.S))
        want = samhita_of(n)
        got = iast.nfc(join_dev(rows))
        if got != want:
            raise SystemExit(f"v{n}: slice join ≠ samhita")
        lines = ["pada_dev\tpada_iast\tslice_dev\tslice_iast\tafter\tmeaning"]
        for pada, sl, after, meaning in rows:
            lines.append(
                "\t".join(
                    [
                        pada,
                        iast.to_iast(pada),
                        sl,
                        iast.to_iast(sl),
                        after,
                        meaning.replace("\t", " "),
                    ]
                )
            )
        padas = "\n".join(lines) + "\n"
        meta = re.sub(r"expected_padas: \d+", f"expected_padas: {len(rows)}", fences["meta"].rstrip())
        trans = fences.get("translation", "").replace("\n", " ").strip()
        phrase = fences.get("phrase", "\n---\n")
        parts = [p.strip() for p in phrase.split("---")]
        h1 = parts[0] if parts else ""
        h2 = parts[1] if len(parts) > 1 else ""
        new = (
            f"# ddv-{n:02d}\n\n"
            f"```meta\n{meta.strip()}\n```\n\n"
            f"```samhita\n{fences['samhita'].strip(chr(10))}\n```\n\n"
            f"```samhita_iast\n{fences['samhita_iast'].strip(chr(10))}\n```\n\n"
            f"```translation\n{trans}\n```\n\n"
            f"```phrase\n{h1}\n---\n{h2}\n```\n\n"
            f"```padas\n{padas}```\n"
        )
        path.write_text(new, encoding="utf-8")
        print(f"filled ddv-{n:02d} ({len(rows)} padas)")
    return 0


def main() -> int:
    if len(sys.argv) > 1 and sys.argv[1] == "apply":
        return apply()
    return test_all()


if __name__ == "__main__":
    raise SystemExit(main())
