/**
 * Drill card provenance:
 * Cue: Gonda, Concise Elementary Grammar, Exercises III (§ 23), p.98 —
 *   same case drill; First Steps has no short -i/-u paradigm exercise.
 * Endings: lesson masculine śuci (-i) and madhu (-u) tables only.
 * Stems: śuci (printed), agni (swapped -i), guru (swapped -u).
 * Dual omitted: after collapse, stem|du has only 3 distinct spellings.
 * Collapsed: abl=gen sg; nom=voc pl; dat=abl pl.
 */
import type { QuizDeckItem, QuizDeckKind, QuizDirection } from "../../../lib/quiz";

export const pendingDeck = {
  id: "nominals-i-and-u-stems",
  titleEn: "-i and -u stems",
  titleIast: "i-u",
  lessonId: "nominals-i-and-u-stems",
  kind: "grammar" as QuizDeckKind,
  direction: "meaning-iast" as QuizDirection,
  items: [
    // śuci — lesson masculine -i table
    {
      id: "suci-sg-nom",
      dev: "शुचिः",
      iast: "śuciḥ",
      meaning: "śuci as the subject (one)",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-sg-acc",
      dev: "शुचिम्",
      iast: "śucim",
      meaning: "śuci as the object (one)",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-sg-ins",
      dev: "शुचिना",
      iast: "śucinā",
      meaning: "with (one) śuci",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-sg-dat",
      dev: "शुचये",
      iast: "śucaye",
      meaning: "for (one) śuci",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-sg-ablgen",
      dev: "शुचेः",
      iast: "śuceḥ",
      meaning: "from/of (one) śuci",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-sg-loc",
      dev: "शुचौ",
      iast: "śucau",
      meaning: "in (one) śuci",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-sg-voc",
      dev: "शुचे",
      iast: "śuce",
      meaning: "O śuci (one)",
      unit: "word",
      group: "śuci|sg",
    },
    {
      id: "suci-pl-nomvoc",
      dev: "शुचयः",
      iast: "śucayaḥ",
      meaning: "śuci as the subject (many)",
      unit: "word",
      group: "śuci|pl",
    },
    {
      id: "suci-pl-acc",
      dev: "शुचीन्",
      iast: "śucīn",
      meaning: "śuci as the object (many)",
      unit: "word",
      group: "śuci|pl",
    },
    {
      id: "suci-pl-ins",
      dev: "शुचिभिः",
      iast: "śucibhiḥ",
      meaning: "with (many) śuci",
      unit: "word",
      group: "śuci|pl",
    },
    {
      id: "suci-pl-databl",
      dev: "शुचिभ्यः",
      iast: "śucibhyaḥ",
      meaning: "for/from (many) śuci",
      unit: "word",
      group: "śuci|pl",
    },
    {
      id: "suci-pl-gen",
      dev: "शुचीनाम्",
      iast: "śucīnām",
      meaning: "of (many) śuci",
      unit: "word",
      group: "śuci|pl",
    },
    {
      id: "suci-pl-loc",
      dev: "शुचिषु",
      iast: "śuciṣu",
      meaning: "in (many) śuci",
      unit: "word",
      group: "śuci|pl",
    },
    // agni — Gonda III swap; endings as masculine śuci
    {
      id: "agni-sg-nom",
      dev: "अग्निः",
      iast: "agniḥ",
      meaning: "agni as the subject (one)",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-sg-acc",
      dev: "अग्निम्",
      iast: "agnim",
      meaning: "agni as the object (one)",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-sg-ins",
      dev: "अग्निना",
      iast: "agninā",
      meaning: "with (one) agni",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-sg-dat",
      dev: "अग्नये",
      iast: "agnaye",
      meaning: "for (one) agni",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-sg-ablgen",
      dev: "अग्नेः",
      iast: "agneḥ",
      meaning: "from/of (one) agni",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-sg-loc",
      dev: "अग्नौ",
      iast: "agnau",
      meaning: "in (one) agni",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-sg-voc",
      dev: "अग्ने",
      iast: "agne",
      meaning: "O agni (one)",
      unit: "word",
      group: "agni|sg",
    },
    {
      id: "agni-pl-nomvoc",
      dev: "अग्नयः",
      iast: "agnayaḥ",
      meaning: "agni as the subject (many)",
      unit: "word",
      group: "agni|pl",
    },
    {
      id: "agni-pl-acc",
      dev: "अग्नीन्",
      iast: "agnīn",
      meaning: "agni as the object (many)",
      unit: "word",
      group: "agni|pl",
    },
    {
      id: "agni-pl-ins",
      dev: "अग्निभिः",
      iast: "agnibhiḥ",
      meaning: "with (many) agni",
      unit: "word",
      group: "agni|pl",
    },
    {
      id: "agni-pl-databl",
      dev: "अग्निभ्यः",
      iast: "agnibhyaḥ",
      meaning: "for/from (many) agni",
      unit: "word",
      group: "agni|pl",
    },
    {
      id: "agni-pl-gen",
      dev: "अग्नीनाम्",
      iast: "agnīnām",
      meaning: "of (many) agni",
      unit: "word",
      group: "agni|pl",
    },
    {
      id: "agni-pl-loc",
      dev: "अग्निषु",
      iast: "agniṣu",
      meaning: "in (many) agni",
      unit: "word",
      group: "agni|pl",
    },
    // guru — Gonda III swap; endings as masculine madhu
    {
      id: "guru-sg-nom",
      dev: "गुरुः",
      iast: "guruḥ",
      meaning: "guru as the subject (one)",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-sg-acc",
      dev: "गुरुम्",
      iast: "gurum",
      meaning: "guru as the object (one)",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-sg-ins",
      dev: "गुरुना",
      iast: "gurunā",
      meaning: "with (one) guru",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-sg-dat",
      dev: "गुरवे",
      iast: "gurave",
      meaning: "for (one) guru",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-sg-ablgen",
      dev: "गुरोः",
      iast: "guroḥ",
      meaning: "from/of (one) guru",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-sg-loc",
      dev: "गुरौ",
      iast: "gurau",
      meaning: "in (one) guru",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-sg-voc",
      dev: "गुरो",
      iast: "guro",
      meaning: "O guru (one)",
      unit: "word",
      group: "guru|sg",
    },
    {
      id: "guru-pl-nomvoc",
      dev: "गुरवः",
      iast: "guravaḥ",
      meaning: "guru as the subject (many)",
      unit: "word",
      group: "guru|pl",
    },
    {
      id: "guru-pl-acc",
      dev: "गुरून्",
      iast: "gurūn",
      meaning: "guru as the object (many)",
      unit: "word",
      group: "guru|pl",
    },
    {
      id: "guru-pl-ins",
      dev: "गुरुभिः",
      iast: "gurubhiḥ",
      meaning: "with (many) guru",
      unit: "word",
      group: "guru|pl",
    },
    {
      id: "guru-pl-databl",
      dev: "गुरुभ्यः",
      iast: "gurubhyaḥ",
      meaning: "for/from (many) guru",
      unit: "word",
      group: "guru|pl",
    },
    {
      id: "guru-pl-gen",
      dev: "गुरूनाम्",
      iast: "gurūnām",
      meaning: "of (many) guru",
      unit: "word",
      group: "guru|pl",
    },
    {
      id: "guru-pl-loc",
      dev: "गुरुषु",
      iast: "guruṣu",
      meaning: "in (many) guru",
      unit: "word",
      group: "guru|pl",
    },
  ] as QuizDeckItem[],
};
