/**
 * Drill card provenance:
 * Cue: First Steps Towards Sanskrit §8.3 (book pp.145–146 table; p.153
 * grāmāt + vanaṃ / sat + gamaya); Gonda Concise Elementary Grammar §§10–12
 * and Exercises I/III/V (pattanāt, vāk me, tat ca, ariñ jahi, devāṃś ca,
 * aśvāṃs tadā, balavāṃl loke, kṛtam ca). Same before→after shape; nouns
 * swapped (pattana→nagara, sat→etat, tān→aśvān/gajān/narān, vanam→nagaram).
 * Groups are the contact rule. Visarga and absolute-final reduction stay out.
 */
import type { QuizDeckItem, QuizDeckKind, QuizDirection } from "../../../lib/quiz";

export const pendingDeck = {
  id: "sandhi-consonant-sandhi-between-words",
  titleEn: "Consonant sandhi between words",
  titleIast: "vyañjana-sandhi",
  lessonId: "sandhi-consonant-sandhi-between-words",
  kind: "grammar" as QuizDeckKind,
  direction: "meaning-iast" as QuizDirection,
  items: [
    // --- stop|before-voiced ---
    {
      id: "tad-vanam",
      dev: "तद् वनम्",
      iast: "tad vanam",
      meaning: "tat + vanam",
      unit: "sandhi",
      group: "stop|before-voiced",
    },
    {
      id: "tad-udakam",
      dev: "तद् उदकम्",
      iast: "tad udakam",
      meaning: "tat + udakam",
      unit: "sandhi",
      group: "stop|before-voiced",
    },
    {
      id: "gramad-vanam",
      dev: "ग्रामाद् वनम्",
      iast: "grāmād vanam",
      meaning: "grāmāt + vanam",
      unit: "sandhi",
      group: "stop|before-voiced",
    },
    {
      id: "nagarad-agacchati",
      dev: "नगराद् आगच्छति",
      iast: "nagarād āgacchati",
      meaning: "nagarāt + āgacchati",
      unit: "sandhi",
      group: "stop|before-voiced",
    },
    {
      id: "vag-gacchati",
      dev: "वाग् गच्छति",
      iast: "vāg gacchati",
      meaning: "vāk + gacchati",
      unit: "sandhi",
      group: "stop|before-voiced",
    },
    {
      id: "etad-gacchati",
      dev: "एतद् गच्छति",
      iast: "etad gacchati",
      meaning: "etat + gacchati",
      unit: "sandhi",
      group: "stop|before-voiced",
    },
    // --- stop|before-nasal ---
    {
      id: "vang-na",
      dev: "वाङ् न",
      iast: "vāṅ na",
      meaning: "vāk + na",
      unit: "sandhi",
      group: "stop|before-nasal",
    },
    {
      id: "ran-na",
      dev: "राण् न",
      iast: "rāṇ na",
      meaning: "rāṭ + na",
      unit: "sandhi",
      group: "stop|before-nasal",
    },
    {
      id: "tan-na",
      dev: "तन् न",
      iast: "tan na",
      meaning: "tat + na",
      unit: "sandhi",
      group: "stop|before-nasal",
    },
    {
      id: "kakum-na",
      dev: "ककुम् न",
      iast: "kakum na",
      meaning: "kakup + na",
      unit: "sandhi",
      group: "stop|before-nasal",
    },
    {
      id: "vang-me",
      dev: "वाङ् मे",
      iast: "vāṅ me",
      meaning: "vāk + me",
      unit: "sandhi",
      group: "stop|before-nasal",
    },
    // --- stop|before-h ---
    {
      id: "vag-gha",
      dev: "वाग् घ",
      iast: "vāg gha",
      meaning: "vāk + ha",
      unit: "sandhi",
      group: "stop|before-h",
    },
    {
      id: "rad-dha",
      dev: "राड् ढ",
      iast: "rāḍ ḍha",
      meaning: "rāṭ + ha",
      unit: "sandhi",
      group: "stop|before-h",
    },
    {
      id: "tad-dha",
      dev: "तद् ध",
      iast: "tad dha",
      meaning: "tat + ha",
      unit: "sandhi",
      group: "stop|before-h",
    },
    {
      id: "kakub-bha",
      dev: "ककुब् भ",
      iast: "kakub bha",
      meaning: "kakup + ha",
      unit: "sandhi",
      group: "stop|before-h",
    },
    // --- t|assim ---
    {
      id: "tac-citram",
      dev: "तच् चित्रम्",
      iast: "tac citram",
      meaning: "tat + citram",
      unit: "sandhi",
      group: "t|assim",
    },
    {
      id: "taj-jalam",
      dev: "तज् जलम्",
      iast: "taj jalam",
      meaning: "tat + jalam",
      unit: "sandhi",
      group: "t|assim",
    },
    {
      id: "tal-labhasva",
      dev: "तल् लभस्व",
      iast: "tal labhasva",
      meaning: "tat + labhasva",
      unit: "sandhi",
      group: "t|assim",
    },
    {
      id: "tac-chocanti",
      dev: "तच् छोचन्ति",
      iast: "tac chocanti",
      meaning: "tat + śocanti",
      unit: "sandhi",
      group: "t|assim",
    },
    {
      id: "etac-ca",
      dev: "एतच् च",
      iast: "etac ca",
      meaning: "etat + ca",
      unit: "sandhi",
      group: "t|assim",
    },
    {
      id: "etaj-janma",
      dev: "एतज् जन्म",
      iast: "etaj janma",
      meaning: "etat + janma",
      unit: "sandhi",
      group: "t|assim",
    },
    // --- n|before-j ---
    {
      id: "naran-jayami",
      dev: "नराञ् जयामि",
      iast: "narāñ jayāmi",
      meaning: "narān + jayāmi",
      unit: "sandhi",
      group: "n|before-j",
    },
    {
      id: "arin-jahi",
      dev: "अरिञ् जहि",
      iast: "ariñ jahi",
      meaning: "arīn + jahi",
      unit: "sandhi",
      group: "n|before-j",
    },
    {
      id: "asvan-jayati",
      dev: "अश्वाञ् जयति",
      iast: "aśvāñ jayati",
      meaning: "aśvān + jayati",
      unit: "sandhi",
      group: "n|before-j",
    },
    {
      id: "gajan-jayami",
      dev: "गजाञ् जयामि",
      iast: "gajāñ jayāmi",
      meaning: "gajān + jayāmi",
      unit: "sandhi",
      group: "n|before-j",
    },
    // --- n|before-c ---
    {
      id: "tams-caranti",
      dev: "तांश् चरन्ति",
      iast: "tāṃś caranti",
      meaning: "tān + caranti",
      unit: "sandhi",
      group: "n|before-c",
    },
    {
      id: "devams-ca",
      dev: "देवांश् च",
      iast: "devāṃś ca",
      meaning: "devān + ca",
      unit: "sandhi",
      group: "n|before-c",
    },
    {
      id: "asvams-caranti",
      dev: "अश्वांश् चरन्ति",
      iast: "aśvāṃś caranti",
      meaning: "aśvān + caranti",
      unit: "sandhi",
      group: "n|before-c",
    },
    {
      id: "narams-carati",
      dev: "नरांश् चरति",
      iast: "narāṃś carati",
      meaning: "narān + carati",
      unit: "sandhi",
      group: "n|before-c",
    },
    // --- n|before-t ---
    {
      id: "tams-taranti",
      dev: "तांस् तरन्ति",
      iast: "tāṃs taranti",
      meaning: "tān + taranti",
      unit: "sandhi",
      group: "n|before-t",
    },
    {
      id: "asvams-tada",
      dev: "अश्वांस् तदा",
      iast: "aśvāṃs tadā",
      meaning: "aśvān + tadā",
      unit: "sandhi",
      group: "n|before-t",
    },
    {
      id: "gajams-taranti",
      dev: "गजांस् तरन्ति",
      iast: "gajāṃs taranti",
      meaning: "gajān + taranti",
      unit: "sandhi",
      group: "n|before-t",
    },
    {
      id: "narams-tisthanti",
      dev: "नरांस् तिष्ठन्ति",
      iast: "narāṃs tiṣṭhanti",
      meaning: "narān + tiṣṭhanti",
      unit: "sandhi",
      group: "n|before-t",
    },
    // --- n|before-l ---
    {
      id: "taml-labhante",
      dev: "ताँल् लभन्ते",
      iast: "tāṃl labhante",
      meaning: "tān + labhante",
      unit: "sandhi",
      group: "n|before-l",
    },
    {
      id: "balavaml-loke",
      dev: "बलवाँल् लोके",
      iast: "balavāṃl loke",
      meaning: "balavān + loke",
      unit: "sandhi",
      group: "n|before-l",
    },
    {
      id: "mahaml-lokah",
      dev: "महाँल् लोकः",
      iast: "mahāṃl lokaḥ",
      meaning: "mahān + lokaḥ",
      unit: "sandhi",
      group: "n|before-l",
    },
    {
      id: "taml-labhasva",
      dev: "ताँल् लभस्व",
      iast: "tāṃl labhasva",
      meaning: "tān + labhasva",
      unit: "sandhi",
      group: "n|before-l",
    },
    // --- m|before-consonant ---
    {
      id: "vanam-gacchati",
      dev: "वनं गच्छति",
      iast: "vanaṃ gacchati",
      meaning: "vanam + gacchati",
      unit: "sandhi",
      group: "m|before-consonant",
    },
    {
      id: "phalam-vanam",
      dev: "फलं वनम्",
      iast: "phalaṃ vanam",
      meaning: "phalam + vanam",
      unit: "sandhi",
      group: "m|before-consonant",
    },
    {
      id: "krtam-ca",
      dev: "कृतं च",
      iast: "kṛtaṃ ca",
      meaning: "kṛtam + ca",
      unit: "sandhi",
      group: "m|before-consonant",
    },
    {
      id: "nagaram-gacchati",
      dev: "नगरं गच्छति",
      iast: "nagaraṃ gacchati",
      meaning: "nagaram + gacchati",
      unit: "sandhi",
      group: "m|before-consonant",
    },
  ] as QuizDeckItem[],
};
