/**
 * Drill card provenance:
 * - nī-*: lesson naya command grid (printed cells); Gonda §60 p.48 imperative shape on bhṛ → endings on naya
 * - pat-*: Gonda §59/§60 first-class thematic; textbook bhṛ/bhara swapped to pat/pata
 * - ji-*: Gonda §59 first-class (ji → jayati); same command endings on jaya
 */
import type { QuizDeckItem, QuizDeckKind, QuizDirection } from "../../../lib/quiz";

export const pendingDeck = {
  id: "verbs-the-command-mood",
  titleEn: "The command mood",
  titleIast: "loṭ",
  lessonId: "verbs-the-command-mood",
  kind: "grammar" as QuizDeckKind,
  direction: "meaning-iast" as QuizDirection,
  items: [
    {
      id: "ni-cmd-3sg",
      dev: "नयतु",
      iast: "nayatu",
      meaning: "naya, 3rd singular",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-3du",
      dev: "नयताम्",
      iast: "nayatām",
      meaning: "naya, 3rd dual",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-3pl",
      dev: "नयन्तु",
      iast: "nayantu",
      meaning: "naya, 3rd plural",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-2sg",
      dev: "नय",
      iast: "naya",
      meaning: "naya, 2nd singular",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-2du",
      dev: "नयतम्",
      iast: "nayatam",
      meaning: "naya, 2nd dual",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-2pl",
      dev: "नयत",
      iast: "nayata",
      meaning: "naya, 2nd plural",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-1sg",
      dev: "नयानि",
      iast: "nayāni",
      meaning: "naya, 1st singular",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-1du",
      dev: "नयाव",
      iast: "nayāva",
      meaning: "naya, 1st dual",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "ni-cmd-1pl",
      dev: "नयाम",
      iast: "nayāma",
      meaning: "naya, 1st plural",
      unit: "word",
      group: "nī|command",
    },
    {
      id: "pat-cmd-3sg",
      dev: "पततु",
      iast: "patatu",
      meaning: "pata, 3rd singular",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-3du",
      dev: "पतताम्",
      iast: "patatām",
      meaning: "pata, 3rd dual",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-3pl",
      dev: "पतन्तु",
      iast: "patantu",
      meaning: "pata, 3rd plural",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-2sg",
      dev: "पत",
      iast: "pata",
      meaning: "pata, 2nd singular",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-2du",
      dev: "पततम्",
      iast: "patatam",
      meaning: "pata, 2nd dual",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-2pl",
      dev: "पतत",
      iast: "patata",
      meaning: "pata, 2nd plural",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-1sg",
      dev: "पतानि",
      iast: "patāni",
      meaning: "pata, 1st singular",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-1du",
      dev: "पताव",
      iast: "patāva",
      meaning: "pata, 1st dual",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "pat-cmd-1pl",
      dev: "पताम",
      iast: "patāma",
      meaning: "pata, 1st plural",
      unit: "word",
      group: "pat|command",
    },
    {
      id: "ji-cmd-3sg",
      dev: "जयतु",
      iast: "jayatu",
      meaning: "jaya, 3rd singular",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-3du",
      dev: "जयताम्",
      iast: "jayatām",
      meaning: "jaya, 3rd dual",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-3pl",
      dev: "जयन्तु",
      iast: "jayantu",
      meaning: "jaya, 3rd plural",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-2sg",
      dev: "जय",
      iast: "jaya",
      meaning: "jaya, 2nd singular",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-2du",
      dev: "जयतम्",
      iast: "jayatam",
      meaning: "jaya, 2nd dual",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-2pl",
      dev: "जयत",
      iast: "jayata",
      meaning: "jaya, 2nd plural",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-1sg",
      dev: "जयानि",
      iast: "jayāni",
      meaning: "jaya, 1st singular",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-1du",
      dev: "जयाव",
      iast: "jayāva",
      meaning: "jaya, 1st dual",
      unit: "word",
      group: "ji|command",
    },
    {
      id: "ji-cmd-1pl",
      dev: "जयाम",
      iast: "jayāma",
      meaning: "jaya, 1st plural",
      unit: "word",
      group: "ji|command",
    },
  ] as QuizDeckItem[],
};
