import type { LessonBlock } from "../catalog";

export const vowelsAndConsonants: LessonBlock[] = [
  {
    type: "p",
    text: "When a vowel does not follow a consonant, it has its own independent sign. Short and long pairs look related: the long form usually adds a stroke or extra mark.",
  },
  {
    type: "glyphs",
    items: [
      { dev: "अ", iast: "a" },
      { dev: "आ", iast: "ā" },
      { dev: "इ", iast: "i" },
      { dev: "ई", iast: "ī" },
      { dev: "उ", iast: "u" },
      { dev: "ऊ", iast: "ū" },
      { dev: "ऋ", iast: "ṛ" },
      { dev: "ॠ", iast: "ṝ" },
      { dev: "ऌ", iast: "ḷ" },
      { dev: "ॡ", iast: "ḹ", note: "almost never used" },
      { dev: "ए", iast: "e" },
      { dev: "ऐ", iast: "ai" },
      { dev: "ओ", iast: "o" },
      { dev: "औ", iast: "au" },
    ],
  },
  { type: "h2", text: "Consonants" },
  {
    type: "p",
    text: "Every consonant sign below is pronounced with a. So क is ka. They are listed in the traditional grid, by point of pronunciation.",
  },
  {
    type: "glyphs",
    items: [
      { dev: "क", iast: "ka" },
      { dev: "ख", iast: "kha" },
      { dev: "ग", iast: "ga" },
      { dev: "घ", iast: "gha" },
      { dev: "ङ", iast: "ṅa" },
      { dev: "च", iast: "ca" },
      { dev: "छ", iast: "cha" },
      { dev: "ज", iast: "ja" },
      { dev: "झ", iast: "jha" },
      { dev: "ञ", iast: "ña" },
      { dev: "ट", iast: "ṭa" },
      { dev: "ठ", iast: "ṭha" },
      { dev: "ड", iast: "ḍa" },
      { dev: "ढ", iast: "ḍha" },
      { dev: "ण", iast: "ṇa" },
      { dev: "त", iast: "ta" },
      { dev: "थ", iast: "tha" },
      { dev: "द", iast: "da" },
      { dev: "ध", iast: "dha" },
      { dev: "न", iast: "na" },
      { dev: "प", iast: "pa" },
      { dev: "फ", iast: "pha" },
      { dev: "ब", iast: "ba" },
      { dev: "भ", iast: "bha" },
      { dev: "म", iast: "ma" },
      { dev: "य", iast: "ya" },
      { dev: "र", iast: "ra" },
      { dev: "ल", iast: "la" },
      { dev: "व", iast: "va" },
      { dev: "श", iast: "śa" },
      { dev: "ष", iast: "ṣa" },
      { dev: "स", iast: "sa" },
      { dev: "ह", iast: "ha" },
    ],
  },
  { type: "h2", text: "Easy to mix up" },
  {
    type: "p",
    text: "A few shapes sit close together. Drill these pairs until the difference is obvious:",
  },
  {
    type: "glyphs",
    items: [
      { dev: "ख", iast: "kha" },
      { dev: "र", iast: "ra" },
      { dev: "घ", iast: "gha" },
      { dev: "ध", iast: "dha" },
      { dev: "ङ", iast: "ṅa" },
      { dev: "ड", iast: "ḍa" },
      { dev: "च", iast: "ca" },
      { dev: "ज", iast: "ja" },
      { dev: "ट", iast: "ṭa" },
      { dev: "ठ", iast: "ṭha" },
      { dev: "ढ", iast: "ḍha" },
      { dev: "द", iast: "da" },
      { dev: "प", iast: "pa" },
      { dev: "फ", iast: "pha" },
      { dev: "य", iast: "ya" },
      { dev: "ष", iast: "ṣa" },
      { dev: "भ", iast: "bha" },
      { dev: "म", iast: "ma" },
      { dev: "व", iast: "va" },
      { dev: "ब", iast: "ba" },
    ],
  },
];
